//! Spectre rendering.

use super::{Element, LineStyle, Netlist, SPECTRE_CAPACITOR, SPECTRE_RESISTOR, write_line};
use crate::compile::DeviceKind;

const HEADER: LineStyle = LineStyle {
    indent: "",
    continuation: "        ",
    suffix: " \\",
};

const ELEMENT: LineStyle = LineStyle {
    indent: "    ",
    continuation: "        ",
    suffix: " \\",
};

/// Renders `netlist` as a Spectre file of subcircuits.
pub(super) fn render(netlist: &Netlist, width: usize) -> String {
    let mut out = format!(
        "// Spectre netlist generated by Argon.\n// Top cell: {}\nsimulator lang=spectre\n",
        netlist.top()
    );
    for (name, subckt) in netlist.subckts() {
        out.push('\n');
        let header = ["subckt", name]
            .into_iter()
            .map(str::to_owned)
            .chain(subckt.ports.iter().cloned())
            .collect::<Vec<_>>();
        write_line(&mut out, &header, &HEADER, width);
        for element in &subckt.elements {
            let tokens = match element {
                Element::Instance { name, nets, child } => [name.clone()]
                    .into_iter()
                    .chain(parenthesized(nets))
                    .chain([netlist.name(*child).to_owned()])
                    .collect::<Vec<_>>(),
                Element::Device {
                    name,
                    kind,
                    nets,
                    value,
                    model,
                    params,
                } => {
                    let (primitive, value_param) = match kind {
                        DeviceKind::Res => (Some(SPECTRE_RESISTOR), "r"),
                        DeviceKind::Cap => (Some(SPECTRE_CAPACITOR), "c"),
                        _ => (None, ""),
                    };
                    let master = model
                        .as_deref()
                        .or(primitive)
                        .expect("only resistors and capacitors may omit a model");
                    [name.clone()]
                        .into_iter()
                        .chain(parenthesized(nets))
                        .chain([master.to_owned()])
                        .chain(value.iter().map(|value| format!("{value_param}={value}")))
                        .chain(params.iter().map(|(name, value)| format!("{name}={value}")))
                        .collect()
                }
            };
            write_line(&mut out, &tokens, &ELEMENT, width);
        }
        out.push_str(&format!("ends {name}\n"));
    }
    out
}

/// `nets` as tokens inside one pair of parentheses: `(a`, `b`, `c)`.
fn parenthesized(nets: &[String]) -> Vec<String> {
    match nets {
        [] => vec!["()".to_owned()],
        [net] => vec![format!("({net})")],
        [first, middle @ .., last] => [format!("({first}")]
            .into_iter()
            .chain(middle.iter().cloned())
            .chain([format!("{last})")])
            .collect(),
    }
}
