//! SPICE rendering.

use super::{Element, LineStyle, Netlist, write_line};

const LINE: LineStyle = LineStyle {
    indent: "",
    continuation: "+ ",
    suffix: "",
};

/// Renders `netlist` as an ngspice-compatible SPICE file of subcircuits.
pub(super) fn render(netlist: &Netlist, width: usize) -> String {
    let mut out = format!(
        "* SPICE netlist generated by Argon.\n* Top cell: {}\n",
        netlist.top()
    );
    for (name, subckt) in netlist.subckts() {
        out.push('\n');
        let header = [".subckt", name]
            .into_iter()
            .map(str::to_owned)
            .chain(subckt.ports.iter().cloned())
            .collect::<Vec<_>>();
        write_line(&mut out, &header, &LINE, width);
        for element in &subckt.elements {
            let tokens = match element {
                Element::Instance { name, nets, child } => [name.clone()]
                    .into_iter()
                    .chain(nets.iter().cloned())
                    .chain([netlist.name(*child).to_owned()])
                    .collect::<Vec<_>>(),
                Element::Device {
                    name,
                    kind: _,
                    nets,
                    value,
                    model,
                    params,
                } => [name.clone()]
                    .into_iter()
                    .chain(nets.iter().cloned())
                    .chain(value.clone())
                    .chain(model.clone())
                    .chain(params.iter().map(|(name, value)| format!("{name}={value}")))
                    .collect(),
            };
            write_line(&mut out, &tokens, &LINE, width);
        }
        out.push_str(&format!(".ends {name}\n"));
    }
    out
}
