[workspace]

resolver = "2"
members = [
    "crates/analyzer",
    "crates/arc",
    "crates/argon",
    "crates/compiler",
    "crates/gui",
    "crates/sparse-linear-solver",
    "crates/tests",
]

[workspace.lints.rust]
unfulfilled_lint_expectations = "forbid"

[workspace.lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
invalid_codeblock_attributes = "deny"
invalid_rust_codeblocks = "deny"
invalid_html_tags = "deny"
bare_urls = "deny"
redundant_explicit_links = "deny"
private_intra_doc_links = "deny"

[workspace.package]
license = "BSD-3-Clause"

[workspace.dependencies]
anyhow = "1"
cfgrammar = { version = "0.15", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
approx = "0.5"
rust_decimal = "1"
rust_decimal_macros = "1"
indexmap = { version = "2", features = ["serde"] }
im = { package = "imbl", version = "7" }
clap = { version = "4", features = ["derive", "env"] }
rgb = { version = "0.8", features = ["serde"] }
thiserror = "2"
toml = "1"
regex = "1"
arcstr = { version = "1", features = ["serde"] }
itertools = "0.15"
fnv = "1"
tarpc = { version = "0.38", features = ["full"] }
bytes = "1"
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
tower-lsp-server = "0.23"
tempfile = "3"

geometry = { version = "0.7", registry = "substrate" }
enumify = { version = "0.2", registry = "substrate" }
uniquify = { version = "0.4", registry = "substrate" }
