[package]
name = "arc"
version = "0.1.0"
edition = "2024"
license.workspace = true
autobins = false

[dependencies]
anyhow = { workspace = true }
argonc = { version = "0.1.0", path = "../compiler" }
clap = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
